<?php
declare(strict_types=1);
require_once dirname(__DIR__) . '/includes/auth_check.php';
require_once dirname(__DIR__) . '/includes/role_check.php';
require_role(['ngo']);
$pdo = db();
$stmt=$pdo->prepare('SELECT id FROM ngo_profiles WHERE user_id=:u LIMIT 1');$stmt->execute(['u'=>(int)$authUser['id']]);$ngo=$stmt->fetch(); if(!$ngo) exit('NGO profile not found.');
$status=trim((string)($_GET['status']??''));$campaign=intval($_GET['campaign']??0);$from=trim((string)($_GET['from']??''));$to=trim((string)($_GET['to']??''));$search=trim((string)($_GET['search']??''));
$sql="SELECT d.id,d.amount,d.transaction_reference,d.proof_image_url,d.status,d.created_at,c.title campaign_title,m.method_title,u.full_name donor_name,u.email donor_email FROM donations d INNER JOIN campaigns c ON c.id=d.campaign_id INNER JOIN ngo_payment_methods m ON m.id=d.payment_method_id INNER JOIN donor_profiles dp ON dp.id=d.donor_id INNER JOIN users u ON u.id=dp.user_id WHERE d.ngo_id=:n";$p=['n'=>(int)$ngo['id']];
if($status!==''&&in_array($status,['pending','confirmed','rejected','flagged'],true)){$sql.=' AND d.status=:s';$p['s']=$status;} if($campaign>0){$sql.=' AND d.campaign_id=:c';$p['c']=$campaign;} if($from!==''){$sql.=' AND DATE(d.created_at)>=:f';$p['f']=$from;} if($to!==''){$sql.=' AND DATE(d.created_at)<=:t';$p['t']=$to;} if($search!==''){$sql.=' AND (u.full_name LIKE :q OR u.email LIKE :q OR d.transaction_reference LIKE :q)';$p['q']='%'.$search.'%';}
$sql.=' ORDER BY d.created_at DESC';$stmt=$pdo->prepare($sql);$stmt->execute($p);$donations=$stmt->fetchAll();
$stmt=$pdo->prepare("SELECT SUM(CASE WHEN status='pending' THEN 1 ELSE 0 END) pending_count,SUM(CASE WHEN status='confirmed' THEN 1 ELSE 0 END) confirmed_count,SUM(CASE WHEN status='confirmed' THEN amount ELSE 0 END) confirmed_amount,SUM(CASE WHEN status='rejected' THEN 1 ELSE 0 END) rejected_count,SUM(CASE WHEN status='flagged' THEN 1 ELSE 0 END) flagged_count FROM donations WHERE ngo_id=:n");$stmt->execute(['n'=>(int)$ngo['id']]);$summary=$stmt->fetch();
$stmt=$pdo->prepare('SELECT id,title FROM campaigns WHERE ngo_id=:n ORDER BY title ASC');$stmt->execute(['n'=>(int)$ngo['id']]);$campaigns=$stmt->fetchAll();
$pageTitle='Donation Dashboard'; require_once dirname(__DIR__) . '/includes/dashboard_layout_start.php'; require dirname(__DIR__) . '/includes/breadcrumbs.php';
?>
<h1 class="section-title">Donation Dashboard</h1>
<div class="dashboard-widgets" style="margin-bottom:1rem;"><div class="stat-card dashboard-card"><small>Pending proofs</small><h3><?= (int)($summary['pending_count']??0) ?></h3></div><div class="stat-card dashboard-card"><small>Confirmed count</small><h3><?= (int)($summary['confirmed_count']??0) ?></h3></div><div class="stat-card dashboard-card"><small>Confirmed amount</small><h3>PKR <?= number_format((float)($summary['confirmed_amount']??0),2) ?></h3></div><div class="stat-card dashboard-card"><small>Rejected</small><h3><?= (int)($summary['rejected_count']??0) ?></h3></div><div class="stat-card dashboard-card"><small>Flagged</small><h3><?= (int)($summary['flagged_count']??0) ?></h3></div></div>
<div class="glass-card" style="padding:1rem;margin-bottom:1rem;"><form class="form-grid"><select name="status"><option value="">All Status</option><option value="pending">pending</option><option value="confirmed">confirmed</option><option value="rejected">rejected</option><option value="flagged">flagged</option></select><select name="campaign"><option value="0">All Campaigns</option><?php foreach($campaigns as $c): ?><option value="<?= (int)$c['id'] ?>" <?= $campaign===(int)$c['id']?'selected':'' ?>><?= sanitize($c['title']) ?></option><?php endforeach; ?></select><input type="date" name="from" value="<?= sanitize($from) ?>"><input type="date" name="to" value="<?= sanitize($to) ?>"><input name="search" value="<?= sanitize($search) ?>" placeholder="Donor/TID"><button class="gradient-button" type="submit">Filter</button></form></div>
<div class="table-wrapper"><table><thead><tr><th>Donor</th><th>Campaign</th><th>Amount</th><th>Method</th><th>TID</th><th>Screenshot</th><th>Status</th><th>Date</th><th>Action</th></tr></thead><tbody><?php if(!$donations): ?><tr><td colspan="9">No donations found.</td></tr><?php endif; ?><?php foreach($donations as $d): ?><tr><td><?= sanitize($d['donor_name']) ?><br><small><?= sanitize($d['donor_email']) ?></small></td><td><?= sanitize($d['campaign_title']) ?></td><td><?= number_format((float)$d['amount'],2) ?></td><td><?= sanitize($d['method_title']) ?></td><td><?= sanitize($d['transaction_reference']) ?></td><td><button type="button" class="outline-button" data-modal-open="proofModal<?= (int)$d['id'] ?>">Preview</button><div class="modal" id="proofModal<?= (int)$d['id'] ?>"><div class="modal-content glass-card"><button class="outline-button" data-modal-close>Close</button><img src="<?= sanitize($d['proof_image_url']) ?>" alt="Proof screenshot"></div></div></td><td><span class="status-badge"><?= sanitize($d['status']) ?></span></td><td><?= sanitize((string)$d['created_at']) ?></td><td><?php if($d['status']==='pending'): ?><button type="button" class="gradient-button" data-modal-open="actionModal<?= (int)$d['id'] ?>">Action</button><div class="modal" id="actionModal<?= (int)$d['id'] ?>"><div class="modal-content glass-card"><h3>Donation Action</h3><p>Confirm updates campaign collected amount.</p><form method="post" action="<?= APP_URL ?>/ngo/donation_action.php"><input type="hidden" name="csrf_token" value="<?= sanitize(csrf_token()) ?>"><input type="hidden" name="donation_id" value="<?= (int)$d['id'] ?>"><select name="action"><option value="confirm">confirm</option><option value="reject">reject</option><option value="flag">flag</option></select><textarea name="note" placeholder="Required for reject/flag"></textarea><button class="gradient-button" type="submit">Submit</button><button class="outline-button" type="button" data-modal-close>Cancel</button></form></div></div><?php else: ?><span class="badge">Already <?= sanitize($d['status']) ?></span><?php endif; ?></td></tr><?php endforeach; ?></tbody></table></div>
<?php require_once dirname(__DIR__) . '/includes/dashboard_layout_end.php'; ?>
