<?php
declare(strict_types=1);
require_once dirname(__DIR__) . '/includes/auth_check.php';
require_once dirname(__DIR__) . '/includes/role_check.php';
require_once dirname(__DIR__) . '/includes/upload_helper.php';
require_role(['ngo']);
$pdo = db();$campaignId=intval($_GET['id']??0);
$stmt=$pdo->prepare('SELECT np.id AS ngo_profile_id,np.verification_status FROM ngo_profiles np WHERE np.user_id=:u LIMIT 1');$stmt->execute(['u'=>(int)$authUser['id']]);$ngo=$stmt->fetch();if(!$ngo) exit('NGO profile not found.');
$stmt=$pdo->prepare('SELECT * FROM campaigns WHERE id=:id AND ngo_id=:ngo_id LIMIT 1');$stmt->execute(['id'=>$campaignId,'ngo_id'=>(int)$ngo['ngo_profile_id']]);$campaign=$stmt->fetch();if(!$campaign) exit('Campaign not found or unauthorized.');if(!in_array($campaign['status'],['pending','rejected'],true)) exit('Only pending/rejected campaigns can be edited.');
$categories=$pdo->query("SELECT id,name FROM campaign_categories WHERE status='active' AND name <> 'Select category' ORDER BY name ASC")->fetchAll();$errors=[];
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!verify_csrf_token($_POST['csrf_token']??null)) exit('Invalid CSRF token.');
 $title=trim((string)($_POST['title']??''));$description=trim((string)($_POST['description']??''));$targetAmount=(float)($_POST['target_amount']??0);$categoryId=intval($_POST['category_id']??0);$startDate=trim((string)($_POST['start_date']??''));$endDate=trim((string)($_POST['end_date']??''));
 if($title===''||$description===''||$targetAmount<=0||$categoryId<=0||$startDate===''||$endDate==='')$errors[]='All required fields must be valid.'; if($endDate<$startDate)$errors[]='End date must not be before start date.';
 $imageUrl=$campaign['image_url'];$imageFileId=$campaign['imagekit_file_id'];if(!empty($_FILES['campaign_image']['name'])){$upload=upload_to_imagekit($_FILES['campaign_image'],'campaigns');if(empty($upload['success'])){$errors[]=(string)($upload['message']??'Image upload failed.');}else{$imageUrl=$upload['url'];$imageFileId=$upload['fileId'];}}
 if(!$errors){$status=$campaign['status']==='rejected'?'pending':$campaign['status'];$rejectionReason=$campaign['status']==='rejected'?null:$campaign['rejection_reason'];$stmt=$pdo->prepare('UPDATE campaigns SET category_id=:category_id,title=:title,description=:description,target_amount=:target_amount,image_url=:image_url,imagekit_file_id=:imagekit_file_id,start_date=:start_date,end_date=:end_date,status=:status,rejection_reason=:rejection_reason,updated_at=NOW() WHERE id=:id AND ngo_id=:ngo_id');$stmt->execute(['category_id'=>$categoryId,'title'=>$title,'description'=>$description,'target_amount'=>$targetAmount,'image_url'=>$imageUrl,'imagekit_file_id'=>$imageFileId,'start_date'=>$startDate,'end_date'=>$endDate,'status'=>$status,'rejection_reason'=>$rejectionReason,'id'=>$campaignId,'ngo_id'=>(int)$ngo['ngo_profile_id']]);log_activity($pdo,(int)$authUser['id'],'campaign_updated','campaigns',$campaignId,'Campaign edited by NGO');redirect('ngo/my_campaigns.php');}
}
$pageTitle='Edit Campaign';require_once dirname(__DIR__) . '/includes/dashboard_layout_start.php';require dirname(__DIR__) . '/includes/breadcrumbs.php';
?>
<h1 class="section-title">Edit Campaign</h1>
<?php if($errors): ?><div class="toast error"><?= sanitize(implode(' | ',$errors)) ?></div><?php endif; ?>
<form method="post" enctype="multipart/form-data" class="form-card" data-loading-button><input type="hidden" name="csrf_token" value="<?= sanitize(csrf_token()) ?>"><div class="form-grid"><div class="form-group"><label>Title</label><input name="title" value="<?= sanitize($campaign['title']) ?>" required></div><div class="form-group"><label>Category</label><select name="category_id" required><?php foreach($categories as $cat): ?><option value="<?= (int)$cat['id'] ?>" <?= ((int)$cat['id']===(int)$campaign['category_id'])?'selected':'' ?>><?= sanitize($cat['name']) ?></option><?php endforeach; ?></select></div></div><div class="form-group"><label>Description</label><textarea name="description" rows="5" required><?= sanitize($campaign['description']) ?></textarea></div><div class="form-grid"><div class="form-group"><label>Target Amount</label><input name="target_amount" type="number" step="0.01" min="1" value="<?= sanitize((string)$campaign['target_amount']) ?>" required></div><div class="form-group"><label>Campaign Image</label><input name="campaign_image" type="file"></div></div><div class="form-grid"><div class="form-group"><label>Start Date</label><input name="start_date" type="date" value="<?= sanitize((string)$campaign['start_date']) ?>" required></div><div class="form-group"><label>End Date</label><input name="end_date" type="date" value="<?= sanitize((string)$campaign['end_date']) ?>" required></div></div><button class="gradient-button" type="submit">Save</button></form>
<?php require_once dirname(__DIR__) . '/includes/dashboard_layout_end.php'; ?>
