<?php
declare(strict_types=1);
require_once dirname(__DIR__) . '/includes/auth_check.php';
require_once dirname(__DIR__) . '/includes/role_check.php';
require_role(['ngo']);
$pdo = db();
$statusFilter = trim((string)($_GET['status'] ?? ''));
$stmt=$pdo->prepare('SELECT id, verification_status FROM ngo_profiles WHERE user_id=:u LIMIT 1');$stmt->execute(['u'=>(int)$authUser['id']]);$ngoProfile=$stmt->fetch();if(!$ngoProfile) exit('NGO profile not found.');
$sql='SELECT c.*, cc.name category_name FROM campaigns c LEFT JOIN campaign_categories cc ON cc.id=c.category_id WHERE c.ngo_id=:n';$p=['n'=>(int)$ngoProfile['id']];if($statusFilter!=='' && in_array($statusFilter,['pending','approved','rejected','active','completed','temporary_hold'],true)){$sql.=' AND c.status=:s';$p['s']=$statusFilter;} $sql.=' ORDER BY c.created_at DESC';
$stmt=$pdo->prepare($sql);$stmt->execute($p);$campaigns=$stmt->fetchAll();
$pageTitle='My Campaigns';require_once dirname(__DIR__) . '/includes/dashboard_layout_start.php';require dirname(__DIR__) . '/includes/breadcrumbs.php';
?>
<h1 class="section-title">My Campaigns</h1>
<div class="glass-card" style="padding:1rem;margin-bottom:1rem;"><form class="form-grid"><select name="status"><option value="">All Status</option><option value="pending">pending</option><option value="approved">approved</option><option value="rejected">rejected</option><option value="active">active</option><option value="completed">completed</option><option value="temporary_hold">temporary_hold</option></select><button class="gradient-button" type="submit">Filter</button><a class="outline-button" href="<?= APP_URL ?>/ngo/create_campaign.php">Create Campaign</a></form></div>
<div class="grid" style="grid-template-columns:1fr;gap:.75rem;"><?php if(!$campaigns): ?><div class="empty-state glass-card">No campaigns created yet.</div><?php endif; ?><?php foreach($campaigns as $c): $progress=((float)$c['target_amount']>0)?min(100,((float)$c['collected_amount']/(float)$c['target_amount']*100)):0; ?><article class="glass-card" style="padding:1rem;display:grid;grid-template-columns:100px 1fr auto;gap:1rem;align-items:center;"><img src="<?= sanitize(image_or_placeholder((string)($c['image_url']??''),'campaign')) ?>" alt="Campaign image" style="width:100px;height:72px;object-fit:cover;"><div><h3><?= sanitize($c['title']) ?></h3><p><span class="badge"><?= sanitize((string)($c['category_name']??'General')) ?></span> <span class="status-badge"><?= sanitize($c['status']) ?></span></p><p>Target: PKR <?= number_format((float)$c['target_amount'],2) ?> | Collected: PKR <?= number_format((float)$c['collected_amount'],2) ?></p><div class="progress-wrap"><div class="progress-bar" style="width:<?= number_format($progress,2) ?>%"></div></div></div><div style="display:grid;gap:.5rem;"><a class="outline-button" href="<?= APP_URL ?>/ngo/campaign_detail.php?id=<?= (int)$c['id'] ?>">View</a><?php if(in_array($c['status'],['pending','rejected'],true)): ?><a class="gradient-button" href="<?= APP_URL ?>/ngo/edit_campaign.php?id=<?= (int)$c['id'] ?>">Edit</a><?php endif; ?><?php if(in_array($c['status'],['approved','active'],true)): ?><a class="outline-button" href="<?= APP_URL ?>/ngo/campaign_updates.php?campaign_id=<?= (int)$c['id'] ?>">Updates</a><?php endif; ?></div></article><?php endforeach; ?></div>
<?php require_once dirname(__DIR__) . '/includes/dashboard_layout_end.php'; ?>
