<?php
declare(strict_types=1);
require_once dirname(__DIR__) . '/includes/auth_check.php';
require_once dirname(__DIR__) . '/includes/role_check.php';
require_role(['ngo']);
$pdo=db();$stmt=$pdo->prepare('SELECT id FROM ngo_profiles WHERE user_id=:u LIMIT 1');$stmt->execute(['u'=>(int)$authUser['id']]);$ngoId=(int)($stmt->fetchColumn()?:0);
$status=trim((string)($_GET['status']??''));$campaign=intval($_GET['campaign']??0);$search=trim((string)($_GET['search']??''));
$sql="SELECT vc.*, c.title campaign_title, u.full_name,u.email,u.phone,vp.skills,vp.availability FROM volunteer_campaigns vc INNER JOIN campaigns c ON c.id=vc.campaign_id INNER JOIN volunteer_profiles vp ON vp.id=vc.volunteer_id INNER JOIN users u ON u.id=vp.user_id WHERE vc.ngo_id=:n";$p=['n'=>$ngoId];
if($status!==''&&in_array($status,['pending','accepted','rejected','cancelled'],true)){$sql.=' AND vc.status=:s';$p['s']=$status;}if($campaign>0){$sql.=' AND vc.campaign_id=:c';$p['c']=$campaign;}if($search!==''){$sql.=' AND (u.full_name LIKE :q OR u.email LIKE :q)';$p['q']='%'.$search.'%';}
$sql.=' ORDER BY vc.created_at DESC';$stmt=$pdo->prepare($sql);$stmt->execute($p);$rows=$stmt->fetchAll();$stmt=$pdo->prepare('SELECT id,title FROM campaigns WHERE ngo_id=:n ORDER BY title ASC');$stmt->execute(['n'=>$ngoId]);$campaigns=$stmt->fetchAll();
$pageTitle='Volunteer Requests';require_once dirname(__DIR__) . '/includes/dashboard_layout_start.php';require dirname(__DIR__) . '/includes/breadcrumbs.php';
?>
<h1 class="section-title">Volunteer Requests</h1>
<div class="glass-card" style="padding:1rem;margin-bottom:1rem;"><form class="form-grid"><select name="status"><option value="">All</option><option value="pending">pending</option><option value="accepted">accepted</option><option value="rejected">rejected</option><option value="cancelled">cancelled</option></select><select name="campaign"><option value="0">All Campaigns</option><?php foreach($campaigns as $c): ?><option value="<?= (int)$c['id'] ?>" <?= $campaign===(int)$c['id']?'selected':'' ?>><?= sanitize($c['title']) ?></option><?php endforeach; ?></select><input name="search" value="<?= sanitize($search) ?>" placeholder="Volunteer search"><button class="gradient-button" type="submit">Filter</button></form></div>
<div class="table-wrapper"><table><thead><tr><th>Volunteer</th><th>Skills/Availability</th><th>Campaign</th><th>Message</th><th>Status</th><th>Date</th><th>Action</th></tr></thead><tbody><?php if(!$rows): ?><tr><td colspan="7">No volunteer requests found.</td></tr><?php endif; ?><?php foreach($rows as $r): ?><tr><td><?= sanitize($r['full_name']) ?><br><small><?= sanitize($r['email']) ?> | <?= sanitize((string)$r['phone']) ?></small></td><td><?= sanitize((string)$r['skills']) ?><br><small><?= sanitize((string)$r['availability']) ?></small></td><td><?= sanitize($r['campaign_title']) ?></td><td><?= sanitize((string)$r['message']) ?></td><td><span class="status-badge"><?= sanitize($r['status']) ?></span></td><td><?= sanitize((string)$r['created_at']) ?></td><td><?php if($r['status']==='pending'): ?><button class="outline-button" type="button" data-modal-open="vAction<?= (int)$r['id'] ?>">Action</button><div class="modal" id="vAction<?= (int)$r['id'] ?>"><div class="modal-content glass-card"><h3>Volunteer Request Action</h3><form method="post" action="<?= APP_URL ?>/ngo/volunteer_action.php"><input type="hidden" name="csrf_token" value="<?= sanitize(csrf_token()) ?>"><input type="hidden" name="id" value="<?= (int)$r['id'] ?>"><select name="action"><option value="accept">accept</option><option value="reject">reject</option></select><textarea name="note" placeholder="Optional note"></textarea><button class="gradient-button" type="submit">Submit</button><button type="button" class="outline-button" data-modal-close>Cancel</button></form></div></div><?php endif; ?></td></tr><?php endforeach; ?></tbody></table></div>
<?php require_once dirname(__DIR__) . '/includes/dashboard_layout_end.php'; ?>
