<?php
declare(strict_types=1);
require_once dirname(__DIR__) . '/includes/auth_check.php';
require_once dirname(__DIR__) . '/includes/role_check.php';
require_role(['admin']);
$pdo = db();
$status=trim((string)($_GET['status']??''));$ngo=intval($_GET['ngo']??0);$donor=intval($_GET['donor']??0);$campaign=intval($_GET['campaign']??0);$from=trim((string)($_GET['from']??''));$to=trim((string)($_GET['to']??''));$tid=trim((string)($_GET['tid']??''));
$sql="SELECT d.id,d.amount,d.transaction_reference,d.proof_image_url,d.status,d.created_at,du.full_name donor_name,du.email donor_email,du.phone donor_phone,nu.ngo_name,uu.email ngo_email,uu.phone ngo_phone,c.title campaign_title,pm.method_title,pm.method_type FROM donations d INNER JOIN donor_profiles dp ON dp.id=d.donor_id INNER JOIN users du ON du.id=dp.user_id INNER JOIN ngo_profiles nu ON nu.id=d.ngo_id INNER JOIN users uu ON uu.id=nu.user_id INNER JOIN campaigns c ON c.id=d.campaign_id INNER JOIN ngo_payment_methods pm ON pm.id=d.payment_method_id WHERE 1=1";$p=[];
if($status!==''&&in_array($status,['pending','confirmed','rejected','flagged'],true)){$sql.=' AND d.status=:s';$p['s']=$status;} if($ngo>0){$sql.=' AND d.ngo_id=:n';$p['n']=$ngo;} if($donor>0){$sql.=' AND d.donor_id=:d';$p['d']=$donor;} if($campaign>0){$sql.=' AND d.campaign_id=:c';$p['c']=$campaign;} if($from!==''){$sql.=' AND DATE(d.created_at)>=:f';$p['f']=$from;} if($to!==''){$sql.=' AND DATE(d.created_at)<=:t';$p['t']=$to;} if($tid!==''){$sql.=' AND d.transaction_reference LIKE :tid';$p['tid']='%'.$tid.'%';}
$sql.=' ORDER BY d.created_at DESC';$stmt=$pdo->prepare($sql);$stmt->execute($p);$donations=$stmt->fetchAll();
$ngos=$pdo->query('SELECT id,ngo_name FROM ngo_profiles ORDER BY ngo_name ASC')->fetchAll();$donors=$pdo->query('SELECT dp.id,u.full_name FROM donor_profiles dp INNER JOIN users u ON u.id=dp.user_id ORDER BY u.full_name ASC')->fetchAll();$campaigns=$pdo->query('SELECT id,title FROM campaigns ORDER BY title ASC')->fetchAll();
$pageTitle='All Donations'; require_once dirname(__DIR__) . '/includes/dashboard_layout_start.php'; require dirname(__DIR__) . '/includes/breadcrumbs.php';
?>
<h1 class="section-title">All Donations</h1>
<div class="glass-card" style="padding:1rem;margin-bottom:1rem;"><form class="form-grid"><select name="status"><option value="">All Status</option><option value="pending">pending</option><option value="confirmed">confirmed</option><option value="rejected">rejected</option><option value="flagged">flagged</option></select><select name="ngo"><option value="0">All NGOs</option><?php foreach($ngos as $n): ?><option value="<?= (int)$n['id'] ?>" <?= $ngo===(int)$n['id']?'selected':'' ?>><?= sanitize($n['ngo_name']) ?></option><?php endforeach; ?></select><select name="donor"><option value="0">All Donors</option><?php foreach($donors as $d): ?><option value="<?= (int)$d['id'] ?>" <?= $donor===(int)$d['id']?'selected':'' ?>><?= sanitize($d['full_name']) ?></option><?php endforeach; ?></select><select name="campaign"><option value="0">All Campaigns</option><?php foreach($campaigns as $c): ?><option value="<?= (int)$c['id'] ?>" <?= $campaign===(int)$c['id']?'selected':'' ?>><?= sanitize($c['title']) ?></option><?php endforeach; ?></select><input type="date" name="from" value="<?= sanitize($from) ?>"><input type="date" name="to" value="<?= sanitize($to) ?>"><input name="tid" value="<?= sanitize($tid) ?>" placeholder="TID search"><button class="gradient-button" type="submit">Filter</button></form></div>
<div class="table-wrapper"><table><thead><tr><th>Sender (Donor)</th><th>Receiver (NGO)</th><th>Campaign</th><th>Method</th><th>Amount</th><th>TID</th><th>Proof</th><th>Status</th><th>Date</th><th>Detail</th></tr></thead><tbody><?php if(!$donations): ?><tr><td colspan="10">No transactions found.</td></tr><?php endif; ?><?php foreach($donations as $d): ?><tr><td><?= sanitize($d['donor_name']) ?><br><small><?= sanitize($d['donor_email']) ?> | <?= sanitize((string)$d['donor_phone']) ?></small></td><td><?= sanitize($d['ngo_name']) ?><br><small><?= sanitize($d['ngo_email']) ?> | <?= sanitize((string)$d['ngo_phone']) ?></small></td><td><?= sanitize($d['campaign_title']) ?></td><td><?= sanitize($d['method_title']) ?> (<?= sanitize($d['method_type']) ?>)</td><td><?= number_format((float)$d['amount'],2) ?></td><td><?= sanitize($d['transaction_reference']) ?></td><td><button class="outline-button" type="button" data-modal-open="img<?= (int)$d['id'] ?>">Preview</button><div class="modal" id="img<?= (int)$d['id'] ?>"><div class="modal-content glass-card"><button class="outline-button" data-modal-close>Close</button><img src="<?= sanitize($d['proof_image_url']) ?>" alt="Donation proof"></div></div></td><td><span class="status-badge"><?= sanitize($d['status']) ?></span></td><td><?= sanitize((string)$d['created_at']) ?></td><td><a class="gradient-button" href="<?= APP_URL ?>/admin/donation_detail.php?id=<?= (int)$d['id'] ?>">Open</a></td></tr><?php endforeach; ?></tbody></table></div>
<?php require_once dirname(__DIR__) . '/includes/dashboard_layout_end.php'; ?>
