<?php
declare(strict_types=1);
require_once dirname(__DIR__) . '/includes/auth_check.php';
require_once dirname(__DIR__) . '/includes/role_check.php';
require_role(['admin']);
$pdo=db();$id=intval($_GET['id']??0);
$stmt=$pdo->prepare('SELECT dp.*,u.full_name,u.email,u.phone,u.profile_photo_url FROM donor_profiles dp INNER JOIN users u ON u.id=dp.user_id WHERE dp.id=:id LIMIT 1');$stmt->execute(['id'=>$id]);$donor=$stmt->fetch();if(!$donor) exit('Donor not found');
$stmt=$pdo->prepare("SELECT SUM(CASE WHEN status='pending' THEN 1 ELSE 0 END) pending_count,SUM(CASE WHEN status='rejected' THEN 1 ELSE 0 END) rejected_count,SUM(CASE WHEN status='confirmed' THEN 1 ELSE 0 END) confirmed_count,SUM(CASE WHEN status='confirmed' THEN amount ELSE 0 END) confirmed_amount FROM donations WHERE donor_id=:d");$stmt->execute(['d'=>$id]);$summary=$stmt->fetch();
$stmt=$pdo->prepare('SELECT d.*,c.title campaign_title,n.ngo_name FROM donations d INNER JOIN campaigns c ON c.id=d.campaign_id INNER JOIN ngo_profiles n ON n.id=d.ngo_id WHERE d.donor_id=:d ORDER BY d.created_at DESC');$stmt->execute(['d'=>$id]);$history=$stmt->fetchAll();
$stmt=$pdo->prepare('SELECT id,subject,status,created_at FROM reports WHERE reported_user_id=:u OR reporter_user_id=:u ORDER BY created_at DESC LIMIT 20');$stmt->execute(['u'=>(int)$donor['user_id']]);$reports=$stmt->fetchAll();
$stmt=$pdo->prepare('SELECT * FROM admin_notes WHERE target_user_id=:u ORDER BY created_at DESC LIMIT 20');$stmt->execute(['u'=>(int)$donor['user_id']]);$notes=$stmt->fetchAll();
$pageTitle='Donor Detail';require_once dirname(__DIR__) . '/includes/dashboard_layout_start.php';require dirname(__DIR__) . '/includes/breadcrumbs.php';
?>
<h1 class="section-title">Donor Detail</h1>
<div class="glass-card" style="padding:1rem;margin-bottom:1rem;"><img src="<?= sanitize(image_or_placeholder((string)($donor['profile_photo_url']??''),'profile')) ?>" alt="Donor photo" style="width:62px;height:62px;border-radius:50%;object-fit:cover;"> <strong><?= sanitize($donor['full_name']) ?></strong> <span class="badge">donor</span><p><?= sanitize($donor['email']) ?> | <?= sanitize((string)$donor['phone']) ?></p></div>
<div class="dashboard-widgets" style="margin-bottom:1rem;"><div class="stat-card dashboard-card"><small>Total confirmed donations</small><h3><?= (int)($summary['confirmed_count']??0) ?></h3></div><div class="stat-card dashboard-card"><small>Total confirmed amount</small><h3>PKR <?= number_format((float)($summary['confirmed_amount']??0),2) ?></h3></div><div class="stat-card dashboard-card"><small>Pending</small><h3><?= (int)($summary['pending_count']??0) ?></h3></div><div class="stat-card dashboard-card"><small>Rejected</small><h3><?= (int)($summary['rejected_count']??0) ?></h3></div></div>
<div class="table-wrapper"><h3>Donation History</h3><table><thead><tr><th>Campaign</th><th>NGO</th><th>Amount</th><th>TID</th><th>Screenshot</th><th>Status</th><th>Date</th></tr></thead><tbody><?php foreach($history as $h): ?><tr><td><?= sanitize($h['campaign_title']) ?></td><td><?= sanitize($h['ngo_name']) ?></td><td><?= number_format((float)$h['amount'],2) ?></td><td><?= sanitize($h['transaction_reference']) ?></td><td><a class="outline-button" target="_blank" href="<?= sanitize($h['proof_image_url']) ?>">View</a></td><td><span class="status-badge"><?= sanitize($h['status']) ?></span></td><td><?= sanitize((string)$h['created_at']) ?></td></tr><?php endforeach; ?></tbody></table></div>
<div class="grid" style="grid-template-columns:1fr 1fr;margin-top:1rem;"><div class="glass-card" style="padding:1rem;"><h3>Related Reports</h3><?php foreach($reports as $r): ?><p>#<?= (int)$r['id'] ?> <?= sanitize($r['subject']) ?> <span class="status-badge"><?= sanitize($r['status']) ?></span></p><?php endforeach; ?></div><div class="glass-card" style="padding:1rem;"><h3>Admin Notes</h3><?php foreach($notes as $n): ?><p><?= sanitize((string)$n['created_at']) ?> - <?= sanitize($n['note']) ?></p><?php endforeach; ?></div></div>
<?php require_once dirname(__DIR__) . '/includes/dashboard_layout_end.php'; ?>
