<?php
declare(strict_types=1);
require_once dirname(__DIR__) . '/includes/auth_check.php';
require_once dirname(__DIR__) . '/includes/role_check.php';
require_role(['admin']);
$pdo = db();
$status=trim((string)($_GET['status']??''));$category=intval($_GET['category']??0);$ngo=intval($_GET['ngo']??0);$search=trim((string)($_GET['search']??''));
$sql="SELECT c.id,c.title,c.target_amount,c.collected_amount,c.status,c.created_at,np.ngo_name,cc.name category_name FROM campaigns c INNER JOIN ngo_profiles np ON np.id=c.ngo_id LEFT JOIN campaign_categories cc ON cc.id=c.category_id WHERE 1=1";$p=[];
if($status!==''&&in_array($status,['pending','approved','rejected','active','completed','temporary_hold'],true)){$sql.=' AND c.status=:s';$p['s']=$status;} if($category>0){$sql.=' AND c.category_id=:cat';$p['cat']=$category;} if($ngo>0){$sql.=' AND c.ngo_id=:ngo';$p['ngo']=$ngo;} if($search!==''){$sql.=' AND c.title LIKE :q';$p['q']='%'.$search.'%';}
$sql.=' ORDER BY c.created_at DESC';$stmt=$pdo->prepare($sql);$stmt->execute($p);$campaigns=$stmt->fetchAll();
$categories=$pdo->query("SELECT id,name FROM campaign_categories ORDER BY name ASC")->fetchAll();$ngos=$pdo->query("SELECT id,ngo_name FROM ngo_profiles ORDER BY ngo_name ASC")->fetchAll();
$pageTitle='Manage Campaigns';require_once dirname(__DIR__) . '/includes/dashboard_layout_start.php';require dirname(__DIR__) . '/includes/breadcrumbs.php';
?>
<h1 class="section-title">Manage Campaigns</h1>
<div class="glass-card" style="padding:1rem;margin-bottom:1rem;"><form class="form-grid"><select name="status"><option value="">All Status</option><option value="pending">pending</option><option value="approved">approved</option><option value="rejected">rejected</option><option value="active">active</option><option value="completed">completed</option><option value="temporary_hold">temporary_hold</option></select><select name="category"><option value="0">All Categories</option><?php foreach($categories as $c): ?><option value="<?= (int)$c['id'] ?>" <?= $category===(int)$c['id']?'selected':'' ?>><?= sanitize($c['name']) ?></option><?php endforeach; ?></select><select name="ngo"><option value="0">All NGOs</option><?php foreach($ngos as $n): ?><option value="<?= (int)$n['id'] ?>" <?= $ngo===(int)$n['id']?'selected':'' ?>><?= sanitize($n['ngo_name']) ?></option><?php endforeach; ?></select><input name="search" value="<?= sanitize($search) ?>" placeholder="Search title"><button class="gradient-button" type="submit">Filter</button></form></div>
<div class="table-wrapper"><table><thead><tr><th>NGO</th><th>Title</th><th>Category</th><th>Target</th><th>Collected</th><th>Status</th><th>Action</th></tr></thead><tbody><?php if(!$campaigns): ?><tr><td colspan="7">No campaigns found.</td></tr><?php endif; ?><?php foreach($campaigns as $c): ?><tr><td><?= sanitize($c['ngo_name']) ?></td><td><?= sanitize($c['title']) ?></td><td><?= sanitize((string)$c['category_name']) ?></td><td><?= number_format((float)$c['target_amount'],2) ?></td><td><?= number_format((float)$c['collected_amount'],2) ?></td><td><span class="status-badge"><?= sanitize($c['status']) ?></span></td><td><button class="outline-button" type="button" data-modal-open="actionCamp<?= (int)$c['id'] ?>">Action</button><div class="modal" id="actionCamp<?= (int)$c['id'] ?>"><div class="modal-content glass-card"><h3>Update Campaign Status</h3><form method="post" action="<?= APP_URL ?>/admin/campaign_action.php"><input type="hidden" name="csrf_token" value="<?= sanitize(csrf_token()) ?>"><input type="hidden" name="campaign_id" value="<?= (int)$c['id'] ?>"><select name="action"><option value="approve">approve</option><option value="reject">reject</option><option value="activate">activate</option><option value="complete">complete</option><option value="temporary_hold">temporary_hold</option></select><textarea name="reason" placeholder="Reason required for reject/hold"></textarea><button class="gradient-button" type="submit">Apply</button><button class="outline-button" type="button" data-modal-close>Cancel</button></form></div></div></td></tr><?php endforeach; ?></tbody></table></div>
<?php require_once dirname(__DIR__) . '/includes/dashboard_layout_end.php'; ?>
