<?php
declare(strict_types=1);
require_once dirname(__DIR__) . '/includes/auth_check.php';
require_once dirname(__DIR__) . '/includes/role_check.php';
require_role(['admin']);
$pdo=db();$role=trim((string)($_GET['role']??''));$status=trim((string)($_GET['account_status']??''));$search=trim((string)($_GET['search']??''));
$sql='SELECT id,full_name,email,phone,role,profile_photo_url,account_status,created_at FROM users WHERE 1=1';$p=[];if($role!==''){$sql.=' AND role=:r';$p['r']=$role;}if($status!==''){$sql.=' AND account_status=:s';$p['s']=$status;}if($search!==''){$sql.=' AND (full_name LIKE :q OR email LIKE :q OR phone LIKE :q)';$p['q']='%'.$search.'%';}$sql.=' ORDER BY created_at DESC';$stmt=$pdo->prepare($sql);$stmt->execute($p);$users=$stmt->fetchAll();
$pageTitle='Manage Users';require_once dirname(__DIR__) . '/includes/dashboard_layout_start.php';require dirname(__DIR__) . '/includes/breadcrumbs.php';
?>
<h1 class="section-title">Manage Users</h1>
<div class="glass-card" style="padding:1rem;margin-bottom:1rem;"><form class="form-grid"><select name="role"><option value="">All Roles</option><option value="admin">admin</option><option value="donor">donor</option><option value="ngo">ngo</option><option value="volunteer">volunteer</option></select><select name="account_status"><option value="">All Status</option><option value="active">active</option><option value="inactive">inactive</option><option value="blocked">blocked</option><option value="suspended">suspended</option><option value="temporary_hold">temporary_hold</option></select><input name="search" value="<?= sanitize($search) ?>" placeholder="Name/email/phone"><button class="gradient-button" type="submit">Filter</button></form></div>
<div class="table-wrapper"><table><thead><tr><th>User</th><th>Email</th><th>Phone</th><th>Role</th><th>Status</th><th>Created</th><th>Actions</th></tr></thead><tbody><?php if(!$users): ?><tr><td colspan="7">No users found.</td></tr><?php endif; ?><?php foreach($users as $u): ?><tr><td><img src="<?= sanitize(image_or_placeholder((string)($u['profile_photo_url']??''),'profile')) ?>" alt="User photo" style="width:34px;height:34px;border-radius:50%;object-fit:cover;display:inline-block;vertical-align:middle;"> <?= sanitize($u['full_name']) ?></td><td><?= sanitize($u['email']) ?></td><td><?= sanitize((string)$u['phone']) ?></td><td><span class="badge"><?= sanitize($u['role']) ?></span></td><td><span class="status-badge"><?= sanitize($u['account_status']) ?></span></td><td><?= sanitize((string)$u['created_at']) ?></td><td><a class="outline-button" href="<?= APP_URL ?>/admin/user_detail.php?id=<?= (int)$u['id'] ?>">View</a><?php if((int)$u['id']!==(int)$authUser['id']): ?> <button class="gradient-button" type="button" data-modal-open="uAction<?= (int)$u['id'] ?>">Action</button><div class="modal" id="uAction<?= (int)$u['id'] ?>"><div class="modal-content glass-card"><h3>Update User Status</h3><form method="post" action="<?= APP_URL ?>/admin/user_action.php"><input type="hidden" name="csrf_token" value="<?= sanitize(csrf_token()) ?>"><input type="hidden" name="user_id" value="<?= (int)$u['id'] ?>"><select name="action" required><option value="activate">activate</option><option value="block">block</option><option value="suspend">suspend</option><option value="temporary_hold">temporary_hold</option></select><textarea name="reason" placeholder="Reason required for block/suspend/hold"></textarea><button class="gradient-button" type="submit">Apply</button><button class="outline-button" data-modal-close type="button">Cancel</button></form></div></div><?php endif; ?></td></tr><?php endforeach; ?></tbody></table></div>
<?php require_once dirname(__DIR__) . '/includes/dashboard_layout_end.php'; ?>
