<?php
declare(strict_types=1);
require_once dirname(__DIR__) . '/includes/auth_check.php';
require_once dirname(__DIR__) . '/includes/role_check.php';
require_role(['admin']);
$pdo=db();
$status=trim((string)($_GET['status']??''));$type=trim((string)($_GET['report_type']??''));$reporter=trim((string)($_GET['reporter']??''));$reportedUser=trim((string)($_GET['reported_user']??''));$from=trim((string)($_GET['from']??''));$to=trim((string)($_GET['to']??''));
$sql="SELECT r.id,r.subject,r.report_type,r.status,r.created_at,ru.full_name reporter_name,uu.full_name reported_user_name,r.reported_campaign_id,r.reported_donation_id FROM reports r INNER JOIN users ru ON ru.id=r.reporter_user_id LEFT JOIN users uu ON uu.id=r.reported_user_id WHERE 1=1";$p=[];
if($status!==''&&in_array($status,['open','under_review','resolved','rejected'],true)){$sql.=' AND r.status=:s';$p['s']=$status;}if($type!==''&&in_array($type,['fake_payment','fake_ngo','fake_campaign','abuse','fraud','technical_issue','other'],true)){$sql.=' AND r.report_type=:t';$p['t']=$type;}if($reporter!==''){$sql.=' AND ru.full_name LIKE :rp';$p['rp']='%'.$reporter.'%';}if($reportedUser!==''){$sql.=' AND uu.full_name LIKE :ru';$p['ru']='%'.$reportedUser.'%';}if($from!==''){$sql.=' AND DATE(r.created_at)>=:f';$p['f']=$from;}if($to!==''){$sql.=' AND DATE(r.created_at)<=:to';$p['to']=$to;}
$sql.=' ORDER BY r.created_at DESC';$stmt=$pdo->prepare($sql);$stmt->execute($p);$rows=$stmt->fetchAll();
$pageTitle='Reports';require_once dirname(__DIR__) . '/includes/dashboard_layout_start.php';require dirname(__DIR__) . '/includes/breadcrumbs.php';
?>
<h1 class="section-title">Reports / Complaints</h1>
<div class="glass-card" style="padding:1rem;margin-bottom:1rem;"><form class="form-grid"><select name="status"><option value="">All Status</option><option value="open">open</option><option value="under_review">under_review</option><option value="resolved">resolved</option><option value="rejected">rejected</option></select><select name="report_type"><option value="">All Types</option><option value="fake_payment">fake_payment</option><option value="fake_ngo">fake_ngo</option><option value="fake_campaign">fake_campaign</option><option value="abuse">abuse</option><option value="fraud">fraud</option><option value="technical_issue">technical_issue</option><option value="other">other</option></select><input name="reporter" value="<?= sanitize($reporter) ?>" placeholder="Reporter search"><input name="reported_user" value="<?= sanitize($reportedUser) ?>" placeholder="Reported user search"><input type="date" name="from" value="<?= sanitize($from) ?>"><input type="date" name="to" value="<?= sanitize($to) ?>"><button class="gradient-button" type="submit">Filter</button></form></div>
<div class="table-wrapper"><table><thead><tr><th>Reporter</th><th>Reported Target</th><th>Type</th><th>Subject</th><th>Status</th><th>Date</th><th>Action</th></tr></thead><tbody><?php if(!$rows): ?><tr><td colspan="7">No reports found.</td></tr><?php endif; ?><?php foreach($rows as $r): $isPriority=in_array($r['report_type'],['fake_payment','fake_ngo','fraud'],true); ?><tr style="<?= $isPriority?'background:rgba(239,77,117,.08);':'' ?>"><td><?= sanitize($r['reporter_name']) ?></td><td><?= sanitize((string)$r['reported_user_name']) ?><?php if((int)$r['reported_campaign_id']>0): ?><br><small>Campaign #<?= (int)$r['reported_campaign_id'] ?></small><?php endif; ?><?php if((int)$r['reported_donation_id']>0): ?><br><small>Donation #<?= (int)$r['reported_donation_id'] ?></small><?php endif; ?></td><td><span class="badge"><?= sanitize($r['report_type']) ?></span></td><td><?= sanitize($r['subject']) ?></td><td><span class="status-badge"><?= sanitize($r['status']) ?></span></td><td><?= sanitize((string)$r['created_at']) ?></td><td><a class="outline-button" href="<?= APP_URL ?>/admin/report_detail.php?id=<?= (int)$r['id'] ?>">View</a></td></tr><?php endforeach; ?></tbody></table></div>
<?php require_once dirname(__DIR__) . '/includes/dashboard_layout_end.php'; ?>
